### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by programmingdogw** [programmingdogw/chat-space#10]
### _IPアドレス
http://18.179.87.231/
### 備考
応用の部分は未実装（登録済みの人間のサーチを消す部分）
パソコンが今一台なので複数人での確認はしてません

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
